# Generated by Django 5.2.3 on 2025-06-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_option',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(default='Default Option 1', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(default='Default Option 2', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(default='Default Option 3', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(default='Default Option 4', max_length=100),
        ),
    ]
