# Generated by Django 5.2.3 on 2025-06-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_question_correct_option_question_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponse',
            name='selected_option',
            field=models.IntegerField(),
        ),
    ]
