# Generated by Django 5.2.3 on 2025-06-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_alter_userresponse_selected_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='selected_option',
        ),
    ]
