# Generated by Django 5.2.3 on 2025-06-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_remove_userresponse_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='selected_option',
            field=models.IntegerField(default='1'),
        ),
    ]
